<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibreTranslate.Net" Version="1.0.1" />
    <PackageReference Include="NPOI" Version="2.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HotelManager.Data\HotelManager.Data.csproj" />
    <ProjectReference Include="..\HotelManager.Models\HotelManager.Models.csproj" />
  </ItemGroup>

</Project>
